# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_oferta', models.CharField(max_length=100, verbose_name=b'Nom oferta')),
                ('poblacio', models.CharField(max_length=100, verbose_name=b'Poblaci\xc3\xb3')),
                ('telefon', models.CharField(max_length=100, verbose_name=b'Telefon')),
                ('lloc_treball_sofereix', models.CharField(max_length=500, verbose_name=b"Lloc de treball que s'ofereix")),
                ('horari', models.CharField(max_length=100, verbose_name=b'Horari')),
                ('caracteristiques', models.CharField(max_length=900, verbose_name=b'Caracteristiques del treball a realitzar')),
                ('numero_vacants', models.CharField(max_length=100, verbose_name=b'Numero de vacants')),
                ('salari', models.CharField(max_length=100, verbose_name=b'Salari')),
                ('nomempresadelaoferta', models.CharField(blank=True, max_length=1000, null=True)),
                ('empresadelaoferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ofertainscrits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.Oferta')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='oferta_inscrits',
            field=models.ManyToManyField(through='oferta.ofertainscrits', to='student.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertainscrits',
            unique_together=set([('estudiant', 'oferta')]),
        ),
    ]
