# Generated by Django 2.1.5 on 2019-01-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='users',
            new_name='empresadelaoferta',
        ),
    ]
