# Generated by Django 2.1.5 on 2019-01-31 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('oferta', '0003_auto_20190131_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertainscrits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferta.Oferta')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='oferta_inscrits',
            field=models.ManyToManyField(through='oferta.ofertainscrits', to='student.Student'),
        ),
    ]
