# Generated by Django 2.1.5 on 2019-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0004_auto_20190131_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='nomempresadelaoferta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
