# Generated by Django 2.1.5 on 2019-01-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='company',
        ),
        migrations.DeleteModel(
            name='Joboffer',
        ),
    ]
