# Generated by Django 2.1.5 on 2019-01-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cif', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='CIF')),
                ('sector', models.CharField(max_length=500)),
                ('descripcio', models.TextField(max_length=500, verbose_name='Descripció')),
                ('nomResponsable', models.CharField(max_length=500, verbose_name='Nom del responsable')),
                ('cognomResponsable', models.CharField(max_length=500, verbose_name='Cognom del responsable')),
                ('esempresaa', models.BooleanField(default=True)),
                ('esempresaa11', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom del usuari')),
            ],
        ),
    ]
