# Generated by Django 2.1.5 on 2019-01-24 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='cif',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cognomResponsable',
            field=models.CharField(max_length=500, verbose_name='Cognom del responsable'),
        ),
        migrations.AlterField(
            model_name='company',
            name='descripcio',
            field=models.TextField(max_length=500, verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nomResponsable',
            field=models.CharField(max_length=500, verbose_name='Nom del responsable'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom del usuari'),
        ),
    ]
