# Generated by Django 2.1.5 on 2019-01-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='esempresaa11',
        ),
    ]
