# Generated by Django 2.1.5 on 2019-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=None)),
                ('requirements', models.CharField(max_length=1000)),
                ('experience', models.CharField(choices=[('no', 'Experiència no requerida'), ('1', 'Al menys un any'), ('2', 'Al menys dos any'), ('3', 'Més de 3 anys')], help_text='Tens 4 opcions', max_length=1)),
                ('minimum_requirements', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=40000, null=None)),
                ('publicada', models.DateTimeField(auto_now_add=True)),
                ('numero_de_vacants', models.IntegerField(null=None)),
                ('salari', models.CharField(max_length=200, null=None)),
            ],
        ),
    ]
