# Generated by Django 2.1.5 on 2019-01-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_joboffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='publicada',
        ),
    ]
