# Generated by Django 2.1.5 on 2019-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_joboffer_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='minimum_requirements',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='numero_de_vacants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salari',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
