# Generated by Django 2.1.5 on 2019-01-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190125_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='experience',
            field=models.CharField(blank=True, choices=[('no', 'Experiència no requerida'), ('1', 'Al menys un any'), ('2', 'Al menys dos any'), ('3', 'Més de 3 anys')], help_text='Tens 4 opcions', max_length=1, null=True),
        ),
    ]
