# Generated by Django 2.1.5 on 2019-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190125_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.CharField(blank=True, max_length=40000),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience',
            field=models.CharField(choices=[('no', 'Experiència no requerida'), ('1', 'Al menys un any'), ('2', 'Al menys dos any'), ('3', 'Més de 3 anys')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='minimum_requirements',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='numero_de_vacants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salari',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
