# Generated by Django 2.1.5 on 2019-01-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190126_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
