# Generated by Django 2.1.5 on 2019-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190124_2345'),
        ('company', '0007_delete_joboffer'),
    ]

    operations = [
    ]
