# Generated by Django 2.1.5 on 2019-01-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_joboffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
