# Generated by Django 2.1.5 on 2019-01-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_delete_joboffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
    ]
