# Generated by Django 2.1.5 on 2019-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190124_2345'),
        ('student', '0006_auto_20190126_2010'),
    ]

    operations = [
    ]
