# Generated by Django 2.1.5 on 2019-01-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_delete_joboffer'),
        ('JobOffer', '0002_delete_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joboffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('requirements', models.CharField(max_length=1000)),
                ('experience', models.CharField(choices=[('0', 'Experiència no requerida'), ('1', 'Al menys un any'), ('2', 'Al menys dos any'), ('3', 'Més de 3 anys')], max_length=1, null=True)),
                ('minimum_requirements', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=40000, null=True)),
                ('numero_de_vacants', models.IntegerField(null=True)),
                ('salari', models.CharField(max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
